# AppVeyor for Kmol editor
image: Visual Studio 2017

platform:
- x64

environment:
  matrix:
  - MINGW_DIR: &mingw C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin
    PYTHON_DIR: C:\Python36-x64

  - MINGW_DIR: *mingw
    PYTHON_DIR: C:\Python37-x64

install:

# Environment variables.
- set Path=%PYTHON_DIR%;%Path%
- set Path=%PYTHON_DIR%\Scripts;%Path%
- set Path=%MINGW_DIR%;%Path%

# Show Python.
- python --version
- pip --version

# Upgrade setuptools
- pip install setuptools -U

# Install modules.
- pip install -r requirements.txt
- pip install pyinstaller

# Show tool kits.
- pyinstaller --version
- mingw32-make --version

before_build:
# Clone submodules.
- git submodule update --init --recursive

build_script:
- mingw32-make SHELL=cmd

test: off

artifacts:
- path: dist/kmol-editor-*.exe
  name: kmol-editor

deploy:
- release: Kmol Editor $(APPVEYOR_REPO_TAG_NAME)
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: ""
  provider: GitHub
  auth_token: $(APPVEYOR_TOKEN)
  artifacts: kmol-editor
  force_update: true
  on:
    appveyor_repo_tag: true
    PYTHON_DIR: C:\Python37-x64
